### ISSUE TITLE
Frontend Backend communication Plan

### ISSUE THREAD

**Issue by mahi-pas** [PLAZMAMA/Word_Reader#1]
we need a temporary file called temp.png within codefiles to store what must be operated on. 

Front end must save over the image and back end can draw on it whenever they want

**Comment by mahi-pas** [comment]
Here is our plan for frontend
image stored in canvas element and output in textbox, convert button to initiate backend

canvas function will also be a clickable box which will open a file manager dialogue as well as allow you to copy paste into it

**Comment by PLAZMAMA** [comment]
I think the file should be called predict.png
but everything sounds good
